services:
  db:
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    image: mysql:latest
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ../volumes/db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/override.cnf
    labels:
      org.label-schema.group: "php_backend"

  php_fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
    container_name: php_fpm
    expose:
      - '9000'
    command: bash -c "/usr/sbin/php-fpm8.2"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ../src:/var/www/php_backend
      - ./php-fpm/php.ini:/etc/php/8.2/fpm/conf.d/90-php_backend.ini
      - ./php-fpm/php.ini:/etc/php/8.2/cli/conf.d/90-php_backend.ini
      - ./php-fpm/local.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
      - ./php-fpm/local.ini:/etc/php/8.2/cli/conf.d/99-overrides.ini
    labels:
      org.label-schema.group: "php_backend"

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ../src:/var/www/php_backend
      - ${NGINX_CONFIG}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONFIG}/sites/:/etc/nginx/sites-available
      - ${NGINX_CONFIG}/conf.d/:/etc/nginx/conf.d
      - ${NGINX_CERT}:/etc/nginx-cert
      # - ./nginx/logs/:/var/log  ## Please use it when you need logging. Create ./docker/nginx/logs/nginx/error.log and ./docker/nginx/logs/nginx/error.log before start logging.
    privileged: true
    environment:
      - APP_ENV=${APP_ENV}
    command: bash -c "nginx"
    links:
      - php_fpm
    depends_on:
      - php_fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    labels:
      org.label-schema.group: "php_backend"

  redis:
    container_name: redis
    image: redis
    labels:
      org.label-schema.group: "php_backend"

version: '3'
volumes: { }
